language: cpp
dist: hirsute
compiler: gcc

addons:
  apt:
    packages:
    - cmake
    - libboost1.71-dev
    - libboost-regex1.71-dev

script:
  - mkdir -p build && cd build
  - cmake ..
  - cmake --build .
  - ./tests
