language: cpp
dist: hirsute
compiler: gcc

addons:
  apt:
    packages:
      - cmake
      - valgrind

script:
  - mkdir -p build && cd build
  - cmake ..
  - cmake --build .
  - valgrind -s ./tests
