language: cpp
dist: hirsute
compiler: gcc

addons:
  apt:
    packages:
      - cmake

script:
  - git pull --recurse-submodules
  - mkdir -p build && cd build
  - cmake ..
  - cmake --build .
  - ./tests
