language: cpp
dist: hirsute
compiler: gcc

addons:
  apt:
    packages:
    - cmake
    - libboost-regex-dev

script:
  - git clone https://github.com/catchorg/Catch2 && mkdir catch2_build -p && cd catch2_build && cmake ../Catch2/ && make install && cd ..
  - mkdir -p build && cd build
  - cmake ..
  - cmake --build .
  - ./tests
